---
abstract: 'Log to RabbitMQ'
author:
  - 'Trevor J. Little, E<lt>bundacia@tjlittle.comE<gt>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Log4perl-Appender-RabbitMQ
provides:
  Log::Log4perl::Appender::RabbitMQ:
    file: lib/Log/Log4perl/Appender/RabbitMQ.pm
    version: 0.01
requires:
  Net::RabbitMQ: '>= 0.1.5'
  perl: v5.6.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bundacia/Log-Log4perl-Appender-RabbitMQ
version: 0.01
